# Generated by Django 5.1.6 on 2025-03-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("boss", "Boss"),
                            ("dispatcher", "Dispatcher"),
                            ("manager", "Manager"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                        verbose_name="Position",
                    ),
                ),
                ("age", models.PositiveSmallIntegerField(verbose_name="Age")),
                ("phone", models.CharField(max_length=20, verbose_name="Phone")),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "employees",
            },
        ),
    ]
